#!/bin/sh
# Resolve all dependencies that the application requires to run.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

echo "Installing test and release dependencies..."
python3 -m pip install pytest pylint flake8 pydocstyle twine
